services:
  front-holcim:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7790:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro